import { cache } from "react";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import ResultsDashboard from "@/components/ResultsDashboard";
import WaitlistForm from "@/components/WaitlistForm";
import { getReport } from "@/lib/store";
import type { AnalyzeMarketResponse } from "@/lib/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// getReport hits the KV store / filesystem directly (not `fetch`), so it
// isn't covered by Next's automatic fetch memoization. Wrapping it in React's
// `cache()` dedupes the lookup between `generateMetadata` and the page
// component for a single request, avoiding a true double-fetch.
const getCachedReport = cache(getReport);

const SITE_NAME = "Benchmark Scout";

function truncate(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text;
  return `${text.slice(0, maxLength - 1).trimEnd()}…`;
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  const stored = await getCachedReport(id);

  if (!stored) {
    return {
      title: "Report not found",
      description: `This shared ${SITE_NAME} report is unavailable or may have expired.`,
    };
  }

  const data = stored.report as AnalyzeMarketResponse;
  const businessName = data?.input?.businessName?.trim() || "This business";
  const marketLabel = data?.market?.label || data?.input?.market || "its market";

  const title =
    data?.report?.title || `${businessName} Competitor Report | ${SITE_NAME}`;
  const description = data?.report?.executiveSummary
    ? truncate(data.report.executiveSummary, 200)
    : `See how ${businessName} stacks up against local competitors in ${marketLabel}, benchmarked by ${SITE_NAME} from public web signals.`;

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      siteName: SITE_NAME,
      type: "article",
    },
    twitter: {
      card: "summary",
      title,
      description,
    },
  };
}

export default async function SharedReportPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const stored = await getCachedReport(id);
  if (!stored) notFound();

  const data = stored.report as AnalyzeMarketResponse;
  const created = new Date(stored.createdAt);
  const marketLabel = data?.market?.label ? `${data.market.label} - ` : "";

  return (
    <div className="min-h-screen bg-slate-50">
      <header className="border-b border-slate-200 bg-white">
        <div className="mx-auto flex max-w-5xl flex-col gap-3 px-6 py-8 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-xs font-medium uppercase tracking-wide text-indigo-600">
              Shared report
            </p>
            <h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">
              {data?.input?.businessName ?? "Benchmark Scout report"}
            </h1>
            <p className="mt-1 text-sm text-slate-500">
              {marketLabel}
              Generated{" "}
              {created.toLocaleDateString(undefined, {
                year: "numeric",
                month: "short",
                day: "numeric",
              })}
            </p>
          </div>
          <Link
            href="/"
            className="shrink-0 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-indigo-500"
          >
            Run your own report
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-5xl space-y-6 px-6 py-8">
        <ResultsDashboard data={data} />
        <WaitlistForm source="shared-report" reportId={id} />
        <footer className="border-t border-slate-200 pt-6 text-xs leading-relaxed text-slate-500">
          <p>
            This is a read-only snapshot generated by Benchmark Scout from
            public web signals. Data reflects the moment the report was created
            and may since have changed.
          </p>
        </footer>
      </main>
    </div>
  );
}
