import Link from "next/link";
import { notFound } from "next/navigation";
import ResultsDashboard from "@/components/ResultsDashboard";
import WaitlistForm from "@/components/WaitlistForm";
import { getReport } from "@/lib/store";
import type { AnalyzeMarketResponse } from "@/lib/types";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export default async function SharedReportPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const stored = await getReport(id);
  if (!stored) notFound();

  const data = stored.report as AnalyzeMarketResponse;
  const created = new Date(stored.createdAt);
  const marketLabel = data?.market?.label ? `${data.market.label} - ` : "";

  return (
    <div className="min-h-screen bg-slate-50">
      <header className="border-b border-slate-200 bg-white">
        <div className="mx-auto flex max-w-5xl flex-col gap-3 px-6 py-8 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-xs font-medium uppercase tracking-wide text-indigo-600">
              Shared report
            </p>
            <h1 className="mt-1 text-2xl font-bold tracking-tight text-slate-900">
              {data?.input?.businessName ?? "Benchmark Scout report"}
            </h1>
            <p className="mt-1 text-sm text-slate-500">
              {marketLabel}
              Generated{" "}
              {created.toLocaleDateString(undefined, {
                year: "numeric",
                month: "short",
                day: "numeric",
              })}
            </p>
          </div>
          <Link
            href="/"
            className="shrink-0 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-indigo-500"
          >
            Run your own report
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-5xl space-y-6 px-6 py-8">
        <ResultsDashboard data={data} />
        <WaitlistForm source="shared-report" reportId={id} />
        <footer className="border-t border-slate-200 pt-6 text-xs leading-relaxed text-slate-500">
          <p>
            This is a read-only snapshot generated by Benchmark Scout from
            public web signals. Data reflects the moment the report was created
            and may since have changed.
          </p>
        </footer>
      </main>
    </div>
  );
}
